volumes:
  pg_data:

services:
  pg:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/VAR/LIB/POSTGRESQL/DATA
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=encryption_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 5s
  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=vault_token
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_TOKEN=vault_token

