name: CI

on:
  push:
    branches:
      - main   
  pull_request:  

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        RUSTFLAGS: "-D warnings"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: Install cargo-hack
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
          checksum: true

      - name: Check compilation for all features
        run: cargo hack check --each-feature --exclude-no-default-features --exclude-all-features --exclude-features mtls --all-targets
      
      - name: Check compilation for mtls with aes
        run: cargo hack check --features aes,mtls

      - name: Run Clippy
        run: cargo hack clippy --each-feature --exclude-no-default-features --exclude-all-features --exclude-features mtls --all-targets

  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
      
      - name: Check formatting
        shell: bash
        run: cargo +nightly fmt --all --check     
    
